title: "Andrew Chingos"
description: "PhD Researcher in Climate Dynamics"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

include:
  - _pages

minimal_mistakes_skin: "sunrise" # options: air, aqua, contrast, dark, dirt, neon, plum, sunrise

author:
  name: "Andrew Chingos"
  bio: "PhD Researcher in Climate Dynamics"
  location: "University of St Andrews, Scotland"
  avatar: "/assets/headShotCropped.jpg"

sidebar:
  nav: ""